name: Deploy no Servidor de Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      
    - name: Executar deploy via SSH
      run: |
        ssh ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }} << 'EOF'
          cd /home/deploy/DockerDeploy
          sudo git pull origin main
          sudo docker build -t app:latest .
          sudo docker stop app-production || true
          sudo docker rm app-production || true
          sudo docker run -d --name app-production -p 80:80 app:latest
        EOF
